-- Seed public.speed_passages from data/speed_passages.json.
-- Each row's target_words is derived from the passage's actual whitespace-tokenised
-- word count so the lookup service can pick the closest match for any request.
-- Dollar-quoted strings ($p$...$p$) avoid hand-escaping single quotes.

INSERT INTO public.speed_passages (target_words, text)
VALUES (
    array_length(regexp_split_to_array(trim($p$Debate is not just a competition; it is a powerful educational tool that cultivates critical thinking and communication skills among students. Engaging in debate encourages young minds to explore various perspectives on complex issues. As they research, formulate arguments, and defend their positions, students learn to articulate their thoughts clearly and persuasively. This process fosters confidence and prepares them for real-world challenges. Moreover, the skills developed in debate often translate into improved performance in other academic areas, such as writing and public speaking. The collaborative nature of debate also promotes teamwork and respect for differing opinions—key components of effective citizenship in today’s diverse society.

In addition to enhancing academic skills, debate can significantly enrich the overall school experience. It creates a vibrant culture of intellectual engagement, bringing together students from various backgrounds and interests. Through tournaments and public speaking events, students not only showcase their talents but also form lasting friendships and networks. The thrill of competition, combined with the joy of learning, makes debate a unique extracurricular activity. As schools increasingly recognize the value of debate, it continues to grow in popularity, shaping well-rounded individuals who are ready to tackle the challenges of the future. Ultimately, the lessons learned in debate extend beyond the classroom, equipping students with essential skills for life.$p$), E'\\s+'), 1),
    $p$Debate is not just a competition; it is a powerful educational tool that cultivates critical thinking and communication skills among students. Engaging in debate encourages young minds to explore various perspectives on complex issues. As they research, formulate arguments, and defend their positions, students learn to articulate their thoughts clearly and persuasively. This process fosters confidence and prepares them for real-world challenges. Moreover, the skills developed in debate often translate into improved performance in other academic areas, such as writing and public speaking. The collaborative nature of debate also promotes teamwork and respect for differing opinions—key components of effective citizenship in today’s diverse society.

In addition to enhancing academic skills, debate can significantly enrich the overall school experience. It creates a vibrant culture of intellectual engagement, bringing together students from various backgrounds and interests. Through tournaments and public speaking events, students not only showcase their talents but also form lasting friendships and networks. The thrill of competition, combined with the joy of learning, makes debate a unique extracurricular activity. As schools increasingly recognize the value of debate, it continues to grow in popularity, shaping well-rounded individuals who are ready to tackle the challenges of the future. Ultimately, the lessons learned in debate extend beyond the classroom, equipping students with essential skills for life.$p$
);

INSERT INTO public.speed_passages (target_words, text)
VALUES (
    array_length(regexp_split_to_array(trim($p$Debate is a crucial aspect of education that sharpens students' critical thinking and public speaking skills. In a debate, participants must analyze complex issues, construct coherent arguments, and respond to opposing viewpoints. This process not only enhances their ability to think on their feet but also fosters respect for diverse perspectives. Moreover, engaging in debates cultivates teamwork; students often collaborate to prepare their cases, sharing insights and strategies. As they practice, they learn to articulate their thoughts clearly and persuasively. These skills are invaluable, extending beyond the classroom into future careers, where effective communication is key. Schools that prioritize debate programs empower students to become informed citizens, capable of discussing important societal issues with confidence. Thus, integrating debate into the curriculum is essential for developing well-rounded, articulate individuals.$p$), E'\\s+'), 1),
    $p$Debate is a crucial aspect of education that sharpens students' critical thinking and public speaking skills. In a debate, participants must analyze complex issues, construct coherent arguments, and respond to opposing viewpoints. This process not only enhances their ability to think on their feet but also fosters respect for diverse perspectives. Moreover, engaging in debates cultivates teamwork; students often collaborate to prepare their cases, sharing insights and strategies. As they practice, they learn to articulate their thoughts clearly and persuasively. These skills are invaluable, extending beyond the classroom into future careers, where effective communication is key. Schools that prioritize debate programs empower students to become informed citizens, capable of discussing important societal issues with confidence. Thus, integrating debate into the curriculum is essential for developing well-rounded, articulate individuals.$p$
);

INSERT INTO public.speed_passages (target_words, text)
VALUES (
    array_length(regexp_split_to_array(trim($p$Debate is an essential skill that transcends the classroom. It fosters critical thinking, enhances communication, and prepares students for real-world challenges. In a debate, participants must articulate their viewpoints clearly and persuasively. This not only boosts confidence but also encourages respect for differing opinions. For instance, when arguing a point, students learn to anticipate counterarguments, enhancing their analytical abilities. Additionally, debate promotes teamwork and collaboration, as participants often work in pairs or groups to prepare their cases. Schools that incorporate debate into their curricula notice improved academic performance across various subjects. In sports, similar skills are vital—players must strategize, communicate effectively, and adapt quickly during games. Thus, whether in debate or sports, developing these skills in school prepares students for success in any field they choose to pursue.$p$), E'\\s+'), 1),
    $p$Debate is an essential skill that transcends the classroom. It fosters critical thinking, enhances communication, and prepares students for real-world challenges. In a debate, participants must articulate their viewpoints clearly and persuasively. This not only boosts confidence but also encourages respect for differing opinions. For instance, when arguing a point, students learn to anticipate counterarguments, enhancing their analytical abilities. Additionally, debate promotes teamwork and collaboration, as participants often work in pairs or groups to prepare their cases. Schools that incorporate debate into their curricula notice improved academic performance across various subjects. In sports, similar skills are vital—players must strategize, communicate effectively, and adapt quickly during games. Thus, whether in debate or sports, developing these skills in school prepares students for success in any field they choose to pursue.$p$
);
